version: "3.3"

#volumes:
#  flats_db:

services:
  selenium-hub:
    restart: always
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome:4.0.0-20211013
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
    ports:
      - 6900:5900

#    chrome:
#      restart: always
#      image: selenium/node-chrome-debug:3.14.0
#      ports:
#        - 6900:5900
#      depends_on:
#        - selenium-hub
#      environment:
#        HUB_HOST: selenium-hub
#        HUB_PORT_4444_TCP_ADDR: selenium-hub
#        HUB_PORT_4444_TCP_PORT: 4444
#        DBUS_SESSION_BUS_ADDRESS: "/dev/null"
#      links:
#        - selenium-hub:hub

  app:
    build: .
    restart: always
    ports:
      - 5000:5000
    volumes:
        #- flats_db:/db
        - ./db:/usr/app/db   #https://af23-94-140-246-19.eu.ngrok.io