version: "3.3"

services:
  selenium-hub:
    restart: always
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
    ports:
      - 6900:5900

  app:
    build: .
    restart: always
    ports:
      - 5000:5000
    volumes:
        - ./db:/usr/app/db