version: "3.3"

services:
  selenium-hub:
    restart: always
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
    ports:
      - 6900:5900

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 5000:5000
    network_mode: host
    volumes:
        - ./db:/usr/app/db

  mlflow:
    build: ./mlflow
    container_name: mlflow
    ports:
      - 5005:5005
    network_mode: host
    volumes:
      - ./mlflow:/mlflow
    #environment:
      #BACKEND_URI: sqlite:////mlflow/mlflow.db
      #ARTIFACT_ROOT: /mlflow/artifacts
    command: 'mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0 --port 5005'
